from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class Communicator(Protocol):
    def send(self, data: Any, dest: int) -> None: ...
    
    def receive(self, source: None) -> Any: ...
    
    def receive_any(self) -> tuple[Any, int]: ...
    
    def get_rank(self) -> int: ...

    def get_size(self) -> int: ...
    